# Generated by Django 2.2.5 on 2019-09-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('capacity', models.SmallIntegerField(verbose_name='Capacity')),
                ('projector_availability', models.BooleanField(default=True, verbose_name='Projector availability')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('comment', models.CharField(max_length=128, verbose_name='Comment')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workshop_RoomsMgt.Room', verbose_name='Rooms')),
            ],
        ),
    ]
